src/Entity/Problem.php
<?php

declare(strict_types=1);

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Ramsey\Uuid\Uuid;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity]
#[Gedmo\Loggable]
class Problem {

    use IdTrait;
    use UuidTrait;

    #[ORM\ManyToOne(targetEntity: ProblemType::class, inversedBy: 'problems')]
    #[ORM\JoinColumn(onDelete: 'CASCADE')]
    #[Gedmo\Versioned]
    private ?ProblemType $problemType = null;

    #[ORM\Column(type: 'string', enumType: Priority::class)]
    #[Gedmo\Versioned]
    private Priority $priority = Priority::Normal;
    
    #[ORM\Column(type: 'boolean')]
    #[Gedmo\Versioned]
    private bool $isOpen = true;
    
    #[ORM\Column(type: 'boolean')]
    #[Gedmo\Versioned]
    private bool $isMaintenance = false;
    
    #[ORM\Column(type: 'text')]
    #[Assert\NotBlank]
    #[Gedmo\Versioned]
    private ?string $content = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    #[Gedmo\Versioned]
    private ?User $assignee = null;

    #[ORM\Column(type: 'datetime')]
    #[Gedmo\Timestampable(on: 'create')]
    private DateTime $createdAt;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    #[Gedmo\Blameable(on: 'create')]
    private ?User $createdBy = null;

    #[Gedmo\Timestampable(on: 'update', field: ['priority', 'isOpen', 'isMaintenance', 'content', 'assignee'])]
    #[ORM\Column(type: 'datetime', nullable: true)]
    private ?DateTime $updatedAt = null;

    #[ORM\ManyToOne(targetEntity: Device::class, inversedBy: 'problems')]
    #[ORM\JoinColumn(nullable: false, onDelete: 'CASCADE')]
    private Device $device;

    /**
     * @var Collection<Comment>
     */
    #[ORM\OneToMany(mappedBy: 'problem', targetEntity: Comment::class)]
    private Collection $comments;

    public function __construct() {
        $this->uuid = Uuid::uuid4();
        $this->comments = new ArrayCollection();
    }

    public function getProblemType(): ?ProblemType {
        return $this->problemType;
    }

    public function setProblemType(ProblemType $problemType): static {
        $this->problemType = $problemType;
        return $this;
    }

    public function getPriority(): Priority {
        return $this->priority;
    }

    public function setPriority(Priority $priority): static {
        $this->priority = $priority;
        return $this;
    }

    public function isOpen(): bool {
        return $this->isOpen;
    }

    public function setIsOpen(bool $isOpen): static {
        $this->isOpen = $isOpen;
        return $this;
    }

    public function isMaintenance(): bool {
        return $this->isMaintenance;
    }

    public function setIsMaintenance(bool $isMaintenance): static {
        $this->isMaintenance = $isMaintenance;
        return $this;
    }

    public function getContent(): ?string {
        return $this->content;
    }

    public function setContent(string $content): static {
        $this->content = $content;
        return $this;
    }

    public function getAssignee(): ?User {
        return $this->assignee;
    }

    public function setAssignee(?User $assignee = null): static {
        $this->assignee = $assignee;
        return $this;
    }

    public function getCreatedAt(): DateTime {
        return $this->createdAt;
    }

    public function getCreatedBy(): ?User {
        return $this->createdBy;
    }

    public function getUpdatedAt(): ?DateTime {
        return $this->updatedAt;
    }

    public function getDevice(): Device {
        return $this->device;
    }

    public function setDevice(Device $device): static {
        $this->device = $device;
        return $this;
    }

    /**
     * @return Collection<Comment>
     */
    public function getComments(): Collection {
        return $this->comments;
    }

    public function addComment(Comment $comment): void {
        $this->comments->add($comment);
    }

    public function removeComment(Comment $comment): void {
        $this->comments->removeElement($comment);
    }
}

src/Entity/ProblemType.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Override;
use Doctrine\Common\Collections\Collection;
use Stringable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Uuid;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity]
class ProblemType implements Stringable {

    use IdTrait;
    use UuidTrait;

    #[ORM\ManyToOne(targetEntity: DeviceType::class, inversedBy: 'problemTypes')]
    #[ORM\JoinColumn]
    #[Assert\NotNull]
    private ?DeviceType $deviceType = null;

    #[ORM\Column(type: 'string')]
    #[Assert\NotBlank]
    private ?string $name = null;

    /**
     * @var Collection<Problem>
     */
    #[ORM\OneToMany(mappedBy: 'problemType', targetEntity: Problem::class)]
    private Collection $problems;

    public function __construct() {
        $this->uuid = Uuid::uuid4();
        $this->problems = new ArrayCollection();
    }

    public function getDeviceType(): ?DeviceType {
        return $this->deviceType;
    }

    public function setDeviceType(DeviceType $deviceType): static {
        $this->deviceType = $deviceType;
        return $this;
    }

    public function getName(): ?string {
        return $this->name;
    }

    public function setName(string $name): static {
        $this->name = $name;
        return $this;
    }

    /**
     * @return Collection<Problem>
     */
    public function getProblems(): Collection {
        return $this->problems;
    }

    #[Override]
    public function __toString(): string {
        return (string) $this->getName();
    }
}

src/Controller/ProblemsController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Device;
use App\Entity\Problem;
use App\Entity\ProblemType as ProblemTypeEntity;
use App\Entity\Room;
use App\Entity\User;
use App\Form\CommentType;
use App\Form\Models\ProblemDto;
use App\Form\ProblemDtoType;
use App\Form\ProblemType;
use App\Helper\Problems\BulkActionManager;
use App\Helper\Problems\History\HistoryResolver;
use App\Repository\CommentRepositoryInterface;
use App\Repository\DeviceRepositoryInterface;
use App\Repository\PaginationQuery;
use App\Repository\ProblemRepositoryInterface;
use App\Repository\ProblemTypeRepository;
use App\Repository\RoomCategoryRepositoryInterface;
use App\Repository\RoomRepositoryInterface;
use App\Security\Voter\CommentVoter;
use App\Security\Voter\ProblemVoter;
use SchulIT\CommonBundle\Form\ConfirmType;
use Symfony\Bridge\Doctrine\Attribute\MapEntity;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Attribute\MapQueryParameter;
use Symfony\Component\HttpKernel\Attribute\MapRequestPayload;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Csrf\CsrfTokenManagerInterface;
use Symfony\Component\Security\Http\Attribute\CurrentUser;
use Symfony\Contracts\Translation\TranslatorInterface;

class ProblemsController extends AbstractController {
    public const string ASSIGNEE_CSRF_TOKEN_ID = 'problem_assignee';
    public const string BULK_CSRF_TOKEN_ID = 'problem_bulk';
    public const string STATUS_CSRF_TOKEN_ID = 'problem_status';
    public const string MAINTENANCE_CSRF_TOKEN_ID = 'problem_maintenance';

    public function __construct(private readonly ProblemRepositoryInterface $problemRepository, private readonly CommentRepositoryInterface $commentRepository)
    {
    }

    #[Route(path: '/problems/add', name: 'new_problem')]
    public function add(Request $request): RedirectResponse|Response {
        $problemDto = new ProblemDto();

        $form = $this->createForm(ProblemDtoType::class, $problemDto);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $lastUuid = null;
            $problems = 0;

            foreach($problemDto->getDevices() as $device) {
                $problem = (new Problem())
                    ->setContent($problemDto->getContent())
                    ->setProblemType($problemDto->getProblemType())
                    ->setPriority($problemDto->getPriority())
                    ->setDevice($device);

                $this->problemRepository->persist($problem);
                ++$problems;
                $lastUuid = $problem->getUuid();
            }

            $this->addFlash('success', 'problems.add.success');

            if($problems === 1) {
                return $this->redirectToRoute('show_problem', [
                    'uuid' => $lastUuid
                ]);

            }

            return $this->redirectToRoute('problems');
        }

        return $this->render('problems/add.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route(path: '/problems/{uuid}/edit', name: 'edit_problem')]
    public function edit(Request $request, #[MapEntity(mapping: ['uuid' => 'uuid'])] Problem $problem): RedirectResponse|Response {
        $this->denyAccessUnlessGranted(ProblemVoter::EDIT, $problem);

        $form = $this->createForm(ProblemType::class, $problem);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $this->problemRepository->persist($problem);

            $this->addFlash('success', 'problems.edit.success');
            return $this->redirectToRoute('show_problem', [ 'uuid' => $problem->getUuid() ]);
        }

        return $this->render('problems/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route(path: '/problems/xhr/devices', name: 'devices_ajax')]
    public function getDevicesXhr(Request $request, RoomRepositoryInterface $roomRepository, TranslatorInterface $translator): JsonResponse {
        $roomId = $request->query->get('room', null);

        if($roomId === null) {
            return new JsonResponse([]);
        }

        $room = $roomRepository->findOneById(intval($roomId));

        if(!$room instanceof Room) {
            throw new NotFoundHttpException();
        }

        $devices = $room->getDevices();

        $result = [ ];

        $result[] = [
            'value' => '',
            'placeholder' => true,
            'label' => $translator->trans('label.choose.device')
        ];

        /** @var Device $device */
        foreach($devices as $device) {
            $result[] = [
                'value' => $device->getId(),
                'label' => sprintf('%s (%s)', $device->getName(), $device->getType()->getName()),
                'customProperties' => [
                    'type' => $device->getType()->getId()
                ]
            ];
        }

        return new JsonResponse($result);
    }

    #[Route(path: '/problems/existing', name: 'existing_problems_ajax')]
    public function xhrExistingProblems(
        #[MapQueryParameter(name: 'type')] int|null $typeId = null,
        #[MapQueryParameter(name: 'devices', filter: FILTER_VALIDATE_INT)] array $deviceIds = [ ]
    ): Response {
        if(!is_array($deviceIds) || count($deviceIds) === 0) {
            return $this->render('problems/existing.html.twig', [
                'problems' => null
            ]);
        }

        $problems = $this->problemRepository->findOpenByDeviceIds($deviceIds, $typeId);

        return $this->render('problems/existing.html.twig', [
            'problems' => $problems
        ]);
    }

    #[Route(path: '/problems/add/ajax', name: 'problem_ajax')]
    public function ajax(
        #[MapQueryParameter(name: 'device')] int $deviceId,
        DeviceRepositoryInterface $deviceRepository,
        TranslatorInterface $translator
    ): JsonResponse {
        /** @var Device $device */
        $device = $deviceRepository
            ->findOneById($deviceId);

        if($device === null) {
            throw new NotFoundHttpException();
        }

        /** @var ProblemTypeEntity[] $types */
        $types = $device->getType()->getProblemTypes();

        $result = [ ];

        $result[] = [
            'value' => '',
            'placeholder' => true,
            'label' => $translator->trans('label.choose.problemtype')
        ];

        foreach($types as $type) {
            $result[] = [
                'value' => $type->getId(),
                'label' => $type->getName()
            ];
        }

        return new JsonResponse($result);
    }

    #[Route(path: '/problems', name: 'problems')]
    public function index(
        RoomRepositoryInterface $roomRepository,
        RoomCategoryRepositoryInterface $roomCategoryRepository,
        #[MapQueryParameter] int $page = 1,
        #[MapQueryParameter(name: 'room')] string|null $roomUuid = null,
        #[MapQueryParameter] string|null $query = null,
        #[MapQueryParameter(name: 'closed')] bool|null $includeClosed = false
    ): RedirectResponse|Response {
        $room = null;

        if($roomUuid !== null) {
            $room = $roomRepository->findOneByUuid($roomUuid);
        }

        return $this->render('problems/index.html.twig', [
            'problems' => $this->problemRepository->findAllPaginated(new PaginationQuery(page: $page), room: $room, query: $query, onlyOpen: !$includeClosed),
            'categories' => $roomCategoryRepository->findAll(),
            'room' => $room,
            'query' => $query,
            'includeClosed' => $includeClosed,
            'csrfTokenBulkId' => self::BULK_CSRF_TOKEN_ID
        ]);
    }

    #[Route(path: '/problems/bulk', name: 'admin_problems_bulk', methods: ['POST'])]
    public function bulk(Request $request, BulkActionManager $bulkActionManager, TranslatorInterface $translator): RedirectResponse {
        if(!$this->isCsrfTokenValid(self::BULK_CSRF_TOKEN_ID, $request->request->get('_csrf_token'))) {
            $this->addFlash('error', 'problems.bulk.csrf');

            return $this->redirectToRoute('problems');
        }

        $action = $request->request->get('action');

        if(!$bulkActionManager->canRunAction($action)) {
            throw new BadRequestHttpException();
        }

        $ids = explode(',', $request->request->get('uuids'));

        if(count($ids) == 0) {
            return $this->redirectToRoute('problems');
        }

        $problems = $this->problemRepository
            ->findByUuids($ids);

        $bulkActionManager->run($problems, $action);

        $this->addFlash('success', $translator->trans('problems.bulk.success', ['%count%' => count($problems) ]));
        return $this->redirectToRoute('problems');
    }

    #[Route(path: '/problems/{uuid}', name: 'show_problem')]
    public function show(Request $request, #[MapEntity(mapping: ['uuid' => 'uuid'])] Problem $problem, HistoryResolver $historyResolver): RedirectResponse|Response {
        $comment = (new Comment())
            ->setProblem($problem);

        $formComment = $this->createForm(CommentType::class, $comment, [ ]);
        $formComment->handleRequest($request);

        if($this->isGranted(CommentVoter::ADD, $problem) && $formComment->isSubmitted() && $formComment->isValid()) {
            $this->commentRepository->persist($comment);

            $this->addFlash('success', 'problems.comments.add.success');
            return $this->redirectToRoute('show_problem', [

templates/problems/add.html.twig
{% extends "main.html.twig" %}

{% block title %}{{ 'problems.add.label'|trans }}{% endblock %}

{% block post_javascript %}
    <script type="text/javascript" src="{{ asset('build/editor.js') }}"></script>
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ path('dashboard') }}">{{ 'dashboard.label'|trans }}</a></li>
        <li class="breadcrumb-item"><a href="{{ path('problems') }}">{{ 'problems.label'|trans }}</a></li>
        <li class="breadcrumb-item">{{ block('title') }}</li>
    </ol>
{% endblock %}

{% block content %}
    {{ form_start(form) }}
    {{ form_row(form.general_group) }}

    <div class="card">
        <div class="card-header">{{ 'problems.add.existing.label'|trans }}</div>

        <div class="card-body" id="existing_problems">
            <div class="bs-callout bs-callout-info">
                <p>{{ 'problems.add.existing.choose'|trans }}</p>
            </div>
        </div>
    </div>

    {{ form_row(form.details_group) }}

    <div class="buttons">
        <button type="submit" class="btn btn-sm btn-primary">
            <i class="fas fa-plus"></i> {{ 'actions.add'|trans }}
        </button>

        <a href="{{ path('problems') }}" class="btn btn-sm btn-secondary">
            {{ 'actions.cancel'|trans }}
        </a>
    </div>
    {{ form_end(form) }}


{% endblock %}

templates/problems/edit.html.twig
{% extends "main.html.twig" %}

{% block title %}{{ 'problems.edit.label'|trans }}{% endblock %}

{% block post_javascript %}
    <script type="text/javascript" src="{{ asset('build/ace/ace.js') }}"></script>
    <script type="text/javascript" src="{{ asset('build/editor.js') }}"></script>
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ path('dashboard') }}">{{ 'dashboard.label'|trans }}</a></li>
        <li class="breadcrumb-item"><a href="{{ path('problems') }}">{{ 'problems.label'|trans }}</a></li>
        <li class="breadcrumb-item">{{ block('title') }}</li>
    </ol>
{% endblock %}

{% block content %}
    {{ form_start(form) }}
    {{ form_widget(form) }}

    <div class="buttons">
        <button type="submit" class="btn btn-sm btn-primary">
            <i class="fas fa-save"></i> {{ 'actions.save'|trans }}
        </button>

        <a href="{{ path('problems') }}" class="btn btn-sm btn-secondary">
            {{ 'actions.cancel'|trans }}
        </a>
    </div>
    {{ form_end(form) }}
{% endblock %}

templates/problems/index.html.twig
{% extends "main.html.twig" %}

{% block post_javascript %}
    <script src="{{ asset('build/problems.js') }}"></script>
{% endblock %}

{% block title %}Probleme{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ path('dashboard') }}">{{ 'dashboard.label'|trans }}</a></li>
        <li class="breadcrumb-item">{{ 'problems.label'|trans }}</li>
    </ol>
{% endblock %}

{% block content %}
    <div class="container-fluid px-0">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex flex-wrap mt-n2">
                            {% if is_granted('ROLE_ADMIN') %}
                                <div class="mt-2 me-2">
                                    <form action="{{ path('admin_problems_bulk') }}" role="form" method="post" class="row row-cols-lg-auto g-1 align-items-center">
                                        <input type="hidden" name="uuids" id="problem-uuids" value="">
                                        <input type="hidden" name="_csrf_token" value="{{ csrf_token(csrfTokenBulkId) }}" />
                                        <div class="input-group input-group-sm">
                                            <select class="form-select" id="action" name="action">
                                                <option value="">{{ 'problems.bulk.placeholder'|trans }}</option>
                                                <option value="mark_solved">{{ 'problems.bulk.solved.label'|trans }}</option>
                                                <option value="set_maintenance">{{ 'problems.bulk.maintenance.label'|trans }}</option>
                                                <option value="unset_maintenance">{{ 'problems.bulk.problem.label'|trans }}</option>
                                                <option value="assignee">{{ 'problems.bulk.take.label'|trans }}</option>
                                            </select>
                                            <button type="submit" class="btn btn-outline-primary" title="{{ 'actions.execute'|trans }}"><i class="fa fa-arrow-right"></i></button>
                                        </div>
                                    </form>
                                </div>
                            {% endif %}

                            <div class="flex-fill mt-2">
                                <form class="row row-cols-lg-auto g-1 align-items-center" method="get">
                                    <div class="col">
                                        <select name="room" id="room" class="form-select form-select-sm" data-trigger="submit">
                                            <option value="">{{ 'label.choose.room'|trans }}</option>
                                            {% for category in categories %}
                                                <optgroup label="{{ category.name }}">
                                                    {% for r in category.rooms %}
                                                        <option value="{{ r.uuid.toString }}" {% if room is not null and r.id == room.id %}selected{% endif %}>{{ r.name }}</option>
                                                    {% endfor %}
                                                </optgroup>
                                            {% endfor %}
                                        </select>
                                    </div>

                                    <div class="col">
                                        <input type="text" name="query" class="form-control form-control-sm" id="query" placeholder="{{ 'problems.search.label'|trans }}" value="{{ query }}">
                                    </div>

                                    <div class="col">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="true" id="closed" name="closed" {% if includeClosed %} checked{% endif %}>
                                            <label class="form-check-label" for="closed">
                                                {{ 'label.filter.solvedproblems'|trans }}
                                            </label>
                                        </div>
                                    </div>

                                    <div class="col">
                                        <button type="submit" class="btn btn-outline-primary btn-sm">
                                            <i class="fas fa-search"></i>
                                        </button>
                                    </div>

                                    {% if room is not null or query is not empty or includeClosed %}
                                        <div class="col">
                                            <a href="{{ path('problems') }}" class="btn btn-outline-primary btn-sm">
                                                <i class="fas fa-times-circle"></i>
                                            </a>
                                        </div>
                                    {% endif %}
                                </form>
                            </div>

                            <div class="ms-auto mt-2">
                                <a href="{{ path('new_problem') }}" class="btn btn-primary btn-sm">
                                    <i class="fas fa-plus"></i> {{ 'problems.add.label'|trans }}
                                </a>
                            </div>
                        </div>


                    </div>

                    <div class="table-responsive">
                        <table class="table table-striped table-hover problems">
                            <colgroup>
                                <col class="column-sm" />
                                <col />
                                <col class="column-md" />
                                <col class="column-md" />
                                <col class="column-lg" />
                            </colgroup>
                            <thead>
                            <tr>
                                <th>
                                    <div class="form-check text-center">
                                        <input id="select-all" class="form-check-input" type="checkbox" data-toggle="select-all" data-select-target="#problem-uuids">
                                    </div>
                                </th>
                                <th>
                                    {{ 'label.problem'|trans }}
                                </th>
                                <th class="hidden-xs hidden-sm">
                                    {{ 'label.priority'|trans }}
                                </th>
                                <th class="hidden-xs hidden-sm">
                                    {{ 'label.status'|trans }}
                                </th>
                                <th>
                                    {{ 'label.last_change'|trans }}
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for problem in problems %}
                                <tr>
                                    <td class="align-middle">
                                        <div class="form-check text-center">
                                            <input id="select-{{ problem.uuid }}" class="form-check-input" type="checkbox" data-toggle="select" data-select-target="#problem-uuids" value="{{ problem.uuid }}">
                                        </div>
                                    </td>
                                    <td class="align-middle">
                                        <a href="{{ path('show_problem', { uuid: problem.uuid }) }}">{{ problem|problem }}</a>

                                        {% if problem.isMaintenance %}
                                            <span class="badge text-bg-secondary">
                                                <i class="fas fa-wrench"></i> {{ 'label.maintenance'|trans }}
                                            </span>
                                        {% endif %}

                                        {% if problem.comments|length > 0 %}
                                            <span class="badge text-bg-secondary" title="{{ 'problems.comments.info'|trans({'%count%': problem.comments|length }) }}">
                                                <i class="fas fa-comments"></i> {{ problem.comments|length }}
                                            </span>
                                        {% endif %}
                                    </td>
                                    <td class="hidden-xs hidden-sm align-middle"><span class="badge text-bg-{{ problem.priority|priority_class }}">{{ problem.priority|priority }}</span></td>
                                    <td class="hidden-xs hidden-sm align-middle">
                                        {% if problem.isOpen %}
                                            <span class="badge text-bg-success">
                                                <i class="fas fa-info-circle"></i> {{ 'status.open'|trans }}
                                            </span>
                                                        {% else %}
                                                            <span class="badge text-bg-danger">
                                                <i class="fas fa-check-circle"></i> {{ 'status.closed'|trans }}
                                            </span>
                                        {% endif %}
                                    </td>
                                    <td class="align-middle">
                                        {% if problem.updatedAt is not null %}
                                            <span title="{{ problem.updatedAt|format_datetime }}">
                                                {{ problem.updatedAt|ago }}
                                            </span>
                                                    {% else %}
                                                        <span title="{{ problem.createdAt|format_datetime }}">
                                                {{ problem.createdAt|ago }}
                                            </span>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>

                    <div class="card-footer">
                        <div class="d-flex">
                            <div class="flex-fill align-self-center">
                                {{ 'problems.count'|trans({'%count%': problems.totalCount}) }}
                            </div>

                            <div class="ms-auto">
                                {% include '@Common/includes/pagination.html.twig' with {
                                    currentFilters: {
                                        room: room != null ? room.uuid : null,
                                        closed: includeClosed,
                                        query: query
                                    },
                                    currentPage: problems.page,
                                    lastPage: problems.totalPages,
                                    paginationPath: 'problems',
                                    showAlwaysFirstAndLast: true
                                } %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/problems/remove.html.twig
{% extends "main.html.twig" %}

{% block title %}{{ 'problems.remove.label'|trans }}{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ path('dashboard') }}">{{ 'dashboard.label'|trans }}</a></li>
        <li class="breadcrumb-item"><a href="{{ path('problems') }}">{{ 'problems.label'|trans }}</a></li>
        <li class="breadcrumb-item">{{ block('title') }}</li>
    </ol>
{% endblock %}

{% block content %}
    {{ form_start(form) }}

    <div class="card border-danger">
        <div class="card-header bg-danger text-white">{{ 'confirm.remove.label'|trans }}</div>

        <div class="card-body">
            {{ form_widget(form.group_general.confirm) }}
        </div>
    </div>

    <div class="buttons">
        <button type="submit" class="btn btn-sm btn-danger">
            <i class="fas fa-save"></i> {{ 'actions.remove'|trans }}
        </button>

        <a href="{{ path('problems') }}" class="btn btn-sm btn-secondary">
            {{ 'actions.cancel'|trans }}
        </a>
    </div>
    {{ form_end(form) }}
{% endblock %}